"""empty message

Revision ID: 2d4279832920
Revises: abd1af815426
Create Date: 2018-05-02 21:32:07.588430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d4279832920'
down_revision = 'abd1af815426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_authority')
    op.add_column('user', sa.Column('authority', sa.VARCHAR(length=100), server_default='normal', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'authority')
    op.create_table('user_authority',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('authority', mysql.VARCHAR(length=100), server_default=sa.text("'admin'"), nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_authority_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
