"""empty message

Revision ID: 327d44e4acb8
Revises: 
Create Date: 2018-01-10 00:47:49.056691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327d44e4acb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), server_default='123456', nullable=False),
    sa.Column('create_time', sa.DATETIME(), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('modify_time', sa.DATETIME(), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('avatar_path', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
