"""empty message

Revision ID: abd1af815426
Revises: 327d44e4acb8
Create Date: 2018-01-11 16:29:52.108283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abd1af815426'
down_revision = '327d44e4acb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), server_default='', nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['label.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), server_default='', nullable=False),
    sa.Column('info', sa.Text(), nullable=False),
    sa.Column('content', mysql.LONGTEXT(), nullable=False),
    sa.Column('create_time', sa.DATETIME(), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('modify_time', sa.DATETIME(), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('good_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('click_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('label_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_authority',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('authority', sa.VARCHAR(length=100), server_default='admin', nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DATETIME(), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('good',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'user_id', name='unique_article_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('good')
    op.drop_table('comment')
    op.drop_table('user_authority')
    op.drop_table('article')
    op.drop_table('label')
    # ### end Alembic commands ###
